site_name: openHPI Linux CLI
site_url: https://maroph.github.io/openhpi_linux-cli_2022/
site_description: Meine Begleitseite zum openHPI Linux CLI Kurs
site_author: Manfred Rosenboom (maroph)

repo_name: GitHub
repo_url: https://github.com/maroph/openhpi_linux-cli_2022/
edit_uri: "blob/main/docs-src"

theme:
    name: material
    palette:
        scheme: default
    font: false
    language: de
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.indexes
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        - navigation.tabs.sticky

nav:
    - Home: index.md
    - Woche:
        - woche/index.md
        - Woche1: woche/woche1.md
        - Woche2: woche/woche2.md
    - Beispiele:
        - samples/index.md
        - Bash Arrays: samples/bash_arrays.md
        - Bash Assoziative Arrays: samples/bash_assoziative_arrays.md
        - Bash Variablen: samples/bash_variables.md
        - date Kommando: samples/date_samples.md
        - Verschiedenes: samples/misc.md
    - Info:
        - Über: info/about.md
        - Lizenz: info/license.md
        - Quellen: info/sources.md
        - Links: info/links.md

docs_dir: docs-src
site_dir: docs

use_directory_urls: false
strict: true

copyright: Copyright (c) 2022 <a href="https://github.com/maroph">Manfred Rosenboom</a>

markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

plugins:
    - git-revision-date
    - search:
        min_search_length: 3

