site_name: openHPI Linux CLI
site_url: https://maroph.github.io/openhpi_linux-cli_2022/
site_description: Meine Begleitseite zum openHPI Linux CLI Kurs
site_author: Manfred Rosenboom (maroph)

repo_name: GitHub
repo_url: https://github.com/maroph/openhpi_linux-cli_2022/
edit_uri: "blob/main/docs-src"

theme:
    name: material
    palette:
        scheme: default
    font: false
    language: de
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        - navigation.tabs.sticky

nav:
    - Home: index.md
    - Woche:
        - Woche1: woche1/index.md
        - Woche2: woche2/index.md
    - Beispiele:
        - Bash Arrays: samples/bash_arrays.md
        - Bash Assoziative Arrays: samples/bash_assoziative_arrays.md
        - Bash Variablen: samples/bash_variables.md
    - Links:
        - Bash:
            - Bash Reference Manual: https://www.gnu.org/software/bash/manual/html_node/index.html
            - Bash FAQ: https://mywiki.wooledge.org/BashFAQ/
            - Rheinwerk Linux: https://openbook.rheinwerk-verlag.de/linux/linux_kap11_001.html
            - SelfLinux: https://www.selflinux.org/selflinux/html/shellprogrammierung.html
        - Linux:
            - JSLinux (Linux im Browser): https://bellard.org/jslinux/vm.html?url=alpine-x86.cfg&mem=192
            - Linux Manpages (die.net): https://linux.die.net/man/
            - Linux Manpages (man.cx): https://man.cx/
            - Rheinwerk Linux: https://openbook.rheinwerk-verlag.de/linux/index.html
    - Info:
        - Über: info/about.md
        - Lizenz: info/license.md
        - Quellen: info/sources.md

docs_dir: docs-src
site_dir: docs

use_directory_urls: false
strict: true

copyright: Copyright (c) 2022 <a href="https://github.com/maroph">Manfred Rosenboom</a>

markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

plugins:
    - git-revision-date
    - search:
        min_search_length: 3

