site_name: openHPI Linux CLI
site_url: https://maroph.github.io/openhpi_linux-cli_2022/
site_description: Meine Begleitseite zum openHPI Linux CLI Kurs
site_author: Manfred Rosenboom (maroph)

repo_name: GitHub
repo_url: https://github.com/maroph/openhpi_linux-cli_2022/
edit_uri: "blob/main/docs-src"

theme:
    name: mkdocs
    highlightjs: true
    hljs_style: github
    nav_style: dark
    navigation_depth: 2

nav:
    - Home: index.md
    - Woche:
        - Woche1: woche1/index.md
        - Woche2: woche2/index.md
    - Links:
        - Bash:
            - Bash Reference Manual: https://www.gnu.org/software/bash/manual/html_node/index.html
            - Rheinwerk Linux: https://openbook.rheinwerk-verlag.de/linux/linux_kap11_001.html
            - SelfLinux: https://www.selflinux.org/selflinux/pdf/shellprogrammierung.pdf
        - Linux:
            - Rheinwerk Linux: https://openbook.rheinwerk-verlag.de/linux/index.html
    - Samples:
        - Bash Array: samples/bash_arrays.md
        - Bash Assoziatives Array: samples/bash_assoziative_arrays.md
    - Info:
        - Über: info/about.md
        - Lizenz: info/license.md
        - Quellen: info/sources.md

docs_dir: docs-src
site_dir: docs

use_directory_urls: false
strict: true

copyright: Copyright (c) 2022 <a href="https://github.com/maroph">Manfred Rosenboom (maroph)</a>

plugins:
    - search:
        min_search_length: 3

